### ISSUE TITLE
Insecure coding pattern: Missing default case in switch statements 

### ISSUE THREAD

**Issue by paser4se** [ToWipf/jasmarty#2]
Greetings, 

We are security researchers and we are looking for insecure coding patterns and configurations in the microservice architecture repositories. In your repository, we have found that your code does not have a default case in the switch statement. According to the Common Weakness Enumeration organization, this is a security weakness. See the link https://cwe.mitre.org/data/definitions/478.html

Source: https://github.com/ToWipf/jasmarty/blob/master/src/main/java/org/wipf/jasmarty/logic/jasmarty/PageConverter.java,  https://github.com/ToWipf/jasmarty/edit/master/src/main/java/org/wipf/jasmarty/logic/jasmarty/extensions/Winamp.java, and https://github.com/ToWipf/jasmarty/blob/master/src/main/java/org/wipf/jasmarty/datatypes/LcdCache.java
Fix: Fix #1 , #3 and #4 

I am interested to know if you agree with the findings. Any feedback is appreciated.

**Comment by ToWipf** [comment]
Hello,

thank you for scanning my repository. I didn't know the default case was so important. I will add these in the future.

**Comment by paser4se** [comment]
Thanks for the feedback. Appreciate it.
